name: Update GitHub Pages with External CSS Files

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main
  # Trigger on a recurring schedule
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  update-css-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Git user name and email
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch the first external CSS file
      - name: Download MinimalNight.css
        run: |
          curl -o MinimalNight.css https://raw.githubusercontent.com/MonolithOrchids/MinimalNightTheme/refs/heads/master/MinimalNight.css

      # Step 4: Fetch the second external CSS file
      - name: Download Sidebar_Icons.css
        run: |
          mkdir -p Addons
          curl -o Addons/Sidebar_Icons.css https://raw.githubusercontent.com/MonolithOrchids/MinimalNightTheme/master/Addons/Sidebar_Icons.css

      # Step 5: Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add MinimalNight.css Addons/Sidebar_Icons.css
          git commit -m "Update CSS files with latest versions" || echo "No changes to commit"
          git push origin main
